server:
  port: 9001

cybershuttle:
  region: "local"
  server:
    port:
      ranges: 9002-9999, 1800-1900
  application:
    timeout: 1800000 # 30 min
    interface:
      id:
        vmd: "VMD_3dc0183b-326e-4c0e-9ee7-9eac7f56a26a"
        jl: "JL"

airavata:
  truststore:
    path: /Users/lahiruj/Projects/airavata/cybershuttle/cybershuttle-server/src/main/resources/truststore.jks

spring:
  application:
    name: cyber-shuttle-server
  datasource:
    url: "jdbc:postgresql://localhost:15432/cybershuttle"
    username: "postgres"
    password: "example"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    root: info


    org:
      hibernate:
        jpa:
          internal:
            EntityManagerFactoryRegistry=DEBUG: